on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
name: Nuget (Desktop)
jobs:
  release:
    name: "Release on Nuget"
    runs-on: windows-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
      - name: "Setup .NET"
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
      - name: "Restore"
        run: dotnet restore Nickvision.Desktop
      - name: "Build"
        run: dotnet build Nickvision.Desktop -c Release --no-restore
      - name: "Pack"
        run: dotnet pack Nickvision.Desktop -c Release --no-build --output .
      - name: "Publish"
        run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json